### ISSUE TITLE
Ошибка в приложении Bulls&Cows

### ISSUE THREAD

**Issue by igor-sirotin** [moslienko/moslienko.github.io#1]
Скачал игру [Bulls&Cows в AppStore](https://apps.apple.com/us/app/bulls-cows-math-game/id1452964449).
Играл простую партию и наткнулся на ошибку.

### Скриншот игры
![IMG_5676](https://user-images.githubusercontent.com/25482501/69345704-a020b000-0c82-11ea-8a86-8f4a6653c003.PNG)

### Ход размышлений
1. Из ходов 4,5,6 => быки: **6** на _позиции-1_ и **1** на _позиции-2_.
1. Из ходов 4,5,6 => цифры **7**,**8**,**9** выбывают из игры.
1. 1 на _позиции-2_ => в ходе 1 коровой является **1** => цифры **2** и **3** выбывают из игры.
1. 1 на _позиции-2_ => в ходе 2 быком является **1** => цифра **4** выбывает из игры.
1. 1 на _позиции-2_ => в ходе 3 быком является **1** => цифры **0** и **5** выбывают из игры.

### Вывод
Из игры выбыли цифры 0,2,3,4,5,7,8,9.
В игре остались цифры: 1,6
Цифр в загаданном числе: 3

По условиям игры цифры не повторяются. Цифр не хватает :)

### P.S.
К сожалению, после того, как я сделал скриншот, я свернул приложение и, когда через пару часов хотел вернуться еще подумать, игра уже была завершена, поэтому дополнительных попыток угадать я сделать не смог. В итоге ответа я не знаю.

**Comment by moslienko** [comment]
Спасибо за отчет об ошибке! 
Точных сроков нет, но надеюсь до конца этого года выпустить апдейт, в том числе и с исправлением  генератора рандомного числа.

**Comment by moslienko** [comment]
Сейчас в App Store доступна новая версия 1.1 в которой это было исправлено :)
